// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataParameter.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { vec4 } from "@carbonenginejs/core-math/vec4";

/** EveSOFDataParameter (eve) - generated from schema shapeHash 148eba9e.... */
@type.define({ className: "EveSOFDataParameter", family: "eve" })
export class EveSOFDataParameter extends CjsModel
{

  /** m_name (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_value (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  value = vec4.create();

  Assign(out = {}, prefix = "")
  {
    out[prefix ? prefix + this.name : this.name] = Array.from(this.value);
    return out;
  }

  static combineArrays(base = [], overrides = null, out = [])
  {
    const validNames = new Set(base.map(value => value.name));
    for (let index = out.length - 1; index >= 0; index--)
    {
      if (!validNames.has(out[index].name)) out.splice(index, 1);
    }
    for (const value of base)
    {
      let result = out.find(candidate => candidate.name === value.name);
      if (!result)
      {
        result = new this();
        result.name = value.name;
        out.push(result);
      }
      const override = overrides?.find(candidate => candidate.name === value.name);
      vec4.copy(result.value, override?.value ?? value.value);
    }
    return out;
  }

}
