// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataLogoSet.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveSOFDataLogo } from "./EveSOFDataLogo.js";

/** EveSOFDataLogoSet (eve) - generated from schema shapeHash 1a77225e.... */
@type.define({ className: "EveSOFDataLogoSet", family: "eve" })
export class EveSOFDataLogoSet extends CjsModel
{

  static LogoType = Object.freeze({
    TYPE_PRIMARY: 0,
    TYPE_SECONDARY: 1,
    TYPE_TERTIARY: 2,
    TYPE_MARKING_01: 3,
    TYPE_MARKING_02: 4,
    TYPE_MAX: 5
  });

  static Types = Object.freeze([
    "Primary",
    "Secondary",
    "Tertiary",
    "Marking_01",
    "Marking_02"
  ]);

  /** m_logos[TYPE_PRIMARY] (EveSOFDataLogoPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataLogo")
  Primary = null;

  /** m_logos[TYPE_SECONDARY] (EveSOFDataLogoPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataLogo")
  Secondary = null;

  /** m_logos[TYPE_TERTIARY] (EveSOFDataLogoPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataLogo")
  Tertiary = null;

  /** m_logos[TYPE_MARKING_01] (EveSOFDataLogoPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataLogo")
  Marking_01 = null;

  /** m_logos[TYPE_MARKING_02] (EveSOFDataLogoPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataLogo")
  Marking_02 = null;

  Has(type)
  {
    const name = this.constructor.Types[type];
    if (name === undefined) throw new ErrSOFLogoSetTypeUnknown(type);
    return this[name] !== null;
  }

  Get(type)
  {
    if (!this.Has(type)) throw new ErrSOFLogoSetTypeNotFound(type);
    return this[this.constructor.Types[type]];
  }

  static combine(base, overrides, out = null)
  {
    out ??= new this();
    if (!base) return out;
    for (const name of this.Types)
    {
      out[name] = EveSOFDataLogo.combine(base[name], overrides?.[name], out[name]);
    }
    return out;
  }

}

export class ErrSOFLogoSetTypeUnknown extends RangeError
{
  constructor(type)
  {
    super("SOF logo set type unknown (" + type + ")");
    this.name = "ErrSOFLogoSetTypeUnknown";
    this.code = "EVE_SOF_LOGO_TYPE_UNKNOWN";
    this.type = type;
  }
}

export class ErrSOFLogoSetTypeNotFound extends Error
{
  constructor(type)
  {
    super("SOF logo set type not found (" + type + ")");
    this.name = "ErrSOFLogoSetTypeNotFound";
    this.code = "EVE_SOF_LOGO_TYPE_NOT_FOUND";
    this.type = type;
  }
}
