// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataDecalIndexBuffer.json.
import { carbon, impl, io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** EveSOFDataDecalIndexBuffer (eve) - generated from schema shapeHash 0c215c06.... */
@type.define({ className: "EveSOFDataDecalIndexBuffer", family: "eve" })
export class EveSOFDataDecalIndexBuffer extends CjsModel
{

  /** indexBuffer (typedArray) [PERSISTONLY] */
  @io.persistOnly
  @type.typedArray("Uint32Array")
  indexBuffer = null;

  /** Carbon method AddIndex (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  AddIndex(index)
  {
    const source = this.indexBuffer ?? [];
    const next = new Uint32Array(source.length + 1);
    next.set(source);
    next[source.length] = Number(index) >>> 0;
    this.indexBuffer = next;
    return true;
  }

  /** Carbon method GetIndices (MAP_METHOD_AND_WRAP). */
  @carbon.method
  @impl.implemented
  GetIndices()
  {
    return Array.from(this.indexBuffer ?? [], value => Number(value) >>> 0);
  }

}
