// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataBoosterShape.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";

/** EveSOFDataBoosterShape (eve) - generated from schema shapeHash 17bbd0bf.... */
@type.define({ className: "EveSOFDataBoosterShape", family: "eve" })
export class EveSOFDataBoosterShape extends CjsModel
{

  /** m_noiseFunction (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseFunction = 0;

  /** m_noiseSpeed (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseSpeed = 0;

  /** m_noiseAmplitureStart (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  noiseAmplitureStart = vec4.create();

  /** m_noiseAmplitureEnd (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  noiseAmplitureEnd = vec4.create();

  /** m_noiseFrequency (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  noiseFrequency = vec4.create();

  /** m_color (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  color = vec4.create();

  get noiseAmplitudeStart()
  {
    return this.noiseAmplitureStart;
  }

  set noiseAmplitudeStart(value)
  {
    vec4.copy(this.noiseAmplitureStart, value);
  }

  get noiseAmplitudeEnd()
  {
    return this.noiseAmplitureEnd;
  }

  set noiseAmplitudeEnd(value)
  {
    vec4.copy(this.noiseAmplitureEnd, value);
  }

  static combine(base, overrides, out = null)
  {
    out ??= new this();
    if (!base && !overrides) return out;
    base ??= out;
    vec4.copy(out.color, selectValue(base, overrides, "color"));
    vec4.copy(out.noiseAmplitureEnd, selectValue(base, overrides, "noiseAmplitureEnd"));
    vec4.copy(out.noiseAmplitureStart, selectValue(base, overrides, "noiseAmplitureStart"));
    vec4.copy(out.noiseFrequency, selectValue(base, overrides, "noiseFrequency"));
    out.noiseFunction = selectValue(base, overrides, "noiseFunction");
    out.noiseSpeed = selectValue(base, overrides, "noiseSpeed");
    return out;
  }

}

function selectValue(base, overrides, name)
{
  const value = overrides?.[name];
  return value !== null && value !== undefined && value !== "" ? value : base[name];
}
