// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataPointLightAttachment.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { quat } from "@carbonenginejs/runtime-utils/quat";
import { vec3 } from "@carbonenginejs/runtime-utils/vec3";

/** EveSOFDataPointLightAttachment (eve) - generated from schema shapeHash e6f58a3b.... */
@type.define({ className: "EveSOFDataPointLightAttachment", family: "eve" })
export class EveSOFDataPointLightAttachment extends CjsModel
{

  /** m_saturation (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  saturation = 1;

  /** m_intensity (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  intensity = 1;

  /** m_translation (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  translation = vec3.create();

  /** m_rotation (Quaternion) [READWRITE, PERSIST] */
  @io.persist
  @type.quat
  rotation = quat.create();

  /** m_innerScaleMultiplier (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  innerScaleMultiplier = 1;

  /** m_outerScaleMultiplier (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  outerScaleMultiplier = 2;

  /** m_noiseAmplitude (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseAmplitude = 0;

  /** m_noiseFrequency (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseFrequency = 1;

  /** m_noiseOctaves (int32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.int32
  noiseOctaves = 1;

  /** m_lightProfilePath (std::wstring) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  lightProfilePath = "";

}
