// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataLogo.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveSOFDataTexture } from "./EveSOFDataTexture.js";

/** EveSOFDataLogo (eve) - generated from schema shapeHash ce883998.... */
@type.define({ className: "EveSOFDataLogo", family: "eve" })
export class EveSOFDataLogo extends CjsModel
{

  /** m_textures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  textures = [];

  Assign(config = {})
  {
    config.textures = this.AssignTextures(config.textures);
    return config;
  }

  AssignTextures(out = {})
  {
    for (const texture of this.textures) texture.Assign(out);
    return out;
  }

  static combine(base, overrides, out = null)
  {
    out ??= new this();
    if (!base) return out;
    EveSOFDataTexture.combineArrays(base.textures, overrides?.textures, out.textures);
    return out;
  }

}
