// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataHullLightSetTexturedPointLight.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { vec3 } from "@carbonenginejs/core-math/vec3";

/** EveSOFDataHullLightSetTexturedPointLight (eve) - generated from schema shapeHash daa6d349.... */
@type.define({ className: "EveSOFDataHullLightSetTexturedPointLight", family: "eve" })
export class EveSOFDataHullLightSetTexturedPointLight extends CjsModel
{

  /** m_data.flags (uint16_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint16
  flags = 1;

  /** m_data.boneIndex (int) [READWRITE, PERSIST] */
  @io.persist
  @type.int32
  boneIndex = -1;

  /** m_name (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_data.position (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  position = vec3.create();

  /** m_data.radius (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  radius = 0;

  /** m_data.innerRadius (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  innerRadius = 0;

  /** m_data.brightness (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  brightness = 0;

  /** m_data.noiseAmplitude (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseAmplitude = 0;

  /** m_data.noiseFrequency (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  noiseFrequency = 1;

  /** m_data.noiseOctaves (int) [READWRITE, PERSIST] */
  @io.persist
  @type.int32
  noiseOctaves = 1;

  /** m_data.texturePath (std::wstring) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  texturePath = "";

}
