// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataHullLightSetTexturedPointLight.json.
import { io, schema, type } from "@carbonenginejs/core-types/schema";
import { EveSOFDataHullLightSetItem } from "./EveSOFDataHullLightSetItem.js";

/** EveSOFDataHullLightSetTexturedPointLight (eve) - generated from schema shapeHash daa6d349.... */
// Carbon derives this from EveSOFDataHullLightSetItem (EveSOFData.h:
// 1410-1417) and re-maps the base surface WITHOUT lightColor, adding
// texturePath (EveSOFData_Blue.cpp:1076-1094): a textured point light takes
// its color from the texture, not the faction color set.
@type.define({ className: "EveSOFDataHullLightSetTexturedPointLight", family: "eve" })
@schema.hideInherited(["lightColor"])
export class EveSOFDataHullLightSetTexturedPointLight extends EveSOFDataHullLightSetItem
{

  /** m_data.texturePath (std::wstring) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  texturePath = "";

}
