// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataHullController.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSOFDataHullController (eve) - generated from schema shapeHash ef1e599d.... */
@type.define({ className: "EveSOFDataHullController", family: "eve" })
export class EveSOFDataHullController extends CjsModel
{

  /** m_buildFilter (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  buildFilter = 0xffffffff;

  /** m_path (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  path = "";

  GetName()
  {
    const slash = this.path.lastIndexOf("/");
    if (slash === -1)
    {
      return "";
    }
    let result = this.path.substring(slash + 1);
    const dot = result.lastIndexOf(".");
    if (dot !== -1)
    {
      result = result.substring(0, dot);
    }
    return result;
  }

}
