// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataHull.json.
import { io, schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { vec3 } from "@carbonenginejs/runtime-utils/vec3";
import { vec4 } from "@carbonenginejs/runtime-utils/vec4";

/** Carbon-authored hull record. */
@type.define({ className: "EveSOFDataHull", family: "eve" })
export class EveSOFDataHull extends CjsModel
{

  static BuildClass = Object.freeze({
    BUILDCLASS_SHIP: 0,
    BUILDCLASS_MOBILE: 1,
    BUILDCLASS_STATIONARY: 2,
    BUILDCLASS_SWARM: 3,
    BUILDCLASS_EXTENSION: 4,
    BUILDCLASS_COUNT: 5
  });

  static ImpactEffectType = Object.freeze({
    IMPACTEFFECT_NONE: 0,
    IMPACTEFFECT_ELLIPSOID: 1,
    IMPACTEFFECT_HULL: 2
  });

  static BuildFilter = Object.freeze({
    STANDALONE: 1,
    NON_INSTANCED_PLACEMENT: 2,
    INSTANCED_PLACEMENT: 4,
    DEFAULT_FILTER: 0xffffffff
  });

  /** m_buildClass (BuildClass - enum BuildClass) [READWRITE, PERSIST, ENUM] */
  @io.persist
  @type.int32
  @schema.enum("BuildClass")
  buildClass = 0;

  /** m_impactEffectType (ImpactEffectType - enum ImpactEffectType) [READWRITE, PERSIST, ENUM] */
  @io.persist
  @type.int32
  @schema.enum("ImpactEffectType")
  impactEffectType = 0;

  /** m_banners (PEveSOFDataHullBannerVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullBanner")
  banners = [];

  /** m_soundEmitters (PEveSOFDataHullSoundEmitterVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullSoundEmitter")
  soundEmitters = [];

  /** m_category (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  category = "";

  /** m_description (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  description = "";

  /** m_locatorSets (PIEveSOFDataHullLocatorSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("IEveSOFDataHullLocatorSet")
  locatorSets = [];

  /** m_isSkinned (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  isSkinned = false;

  /** m_animations (PEveSOFDataHullAnimationVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullAnimation")
  animations = [];

  /** m_children (PEveSOFDataHullChildVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullChild")
  children = [];

  /** m_controllers (PEveSOFDataHullControllerVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullController")
  controllers = [];

  /** m_instancedMeshes (PEveSOFDataInstancedMeshVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataInstancedMesh")
  instancedMeshes = [];

  /** m_modelRotationCurvePath (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  modelRotationCurvePath = "";

  /** m_modelTranslationCurvePath (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  modelTranslationCurvePath = "";

  /** m_childSets (PEveSOFDataHullChildSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullChildSet")
  childSets = [];

  /** m_boundingSphere (Vector4) [READWRITE, PERSIST] */
  @io.persist
  @type.vec4
  boundingSphere = vec4.create();

  /** m_additiveAreas (PEveSOFDataHullAreaVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullArea")
  additiveAreas = [];

  /** m_audioPosition (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  audioPosition = vec3.create();

  /** m_bannerSets (PEveSOFDataHullBannerSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullBannerSet")
  bannerSets = [];

  /** m_booster (EveSOFDataHullBoosterPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataHullBooster")
  booster = null;

  /** m_decalAreas (PEveSOFDataHullAreaVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullArea")
  decalAreas = [];

  /** m_decalSets (PEveSOFDataHullDecalSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullDecalSet")
  decalSets = [];

  /** m_defaultPattern (EveSOFDataPatternPerHullPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataPatternPerHull")
  defaultPattern = null;

  /** m_distortionAreas (PEveSOFDataHullAreaVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullArea")
  distortionAreas = [];

  /** m_shapeEllipsoidCenter (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  shapeEllipsoidCenter = vec3.create();

  /** m_shapeEllipsoidRadius (Vector3) [READWRITE, PERSIST] */
  @io.persist
  @type.vec3
  shapeEllipsoidRadius = vec3.fromValues(-1, -1, -1);

  /** m_hazeSets (PEveSOFDataHullHazeSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullHazeSet")
  hazeSets = [];

  /** m_name (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_lightSets (PEveSOFDataHullLightSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullLightSet")
  lightSets = [];

  /** m_opaqueAreas (PEveSOFDataHullAreaVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullArea")
  opaqueAreas = [];

  /** m_planeSets (PEveSOFDataHullPlaneSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullPlaneSet")
  planeSets = [];

  /** m_geometryResFilePath (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  geometryResFilePath = "";

  /** m_spotlightSets (PEveSOFDataHullSpotlightSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullSpotlightSet")
  spotlightSets = [];

  /** m_spriteLineSets (PEveSOFDataHullSpriteLineSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullSpriteLineSet")
  spriteLineSets = [];

  /** m_spriteSets (PEveSOFDataHullSpriteSetVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullSpriteSet")
  spriteSets = [];

  /** m_transparentAreas (PEveSOFDataHullAreaVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullArea")
  transparentAreas = [];

  /** m_locatorTurrets (PEveSOFDataHullLocatorVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataHullLocator")
  locatorTurrets = [];

  /** m_sof6 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  sof6 = false;

  /** m_enableDynamicBoundingSphere (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  enableDynamicBoundingSphere = false;

  /** m_castShadow (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  castShadow = true;

}
