// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataHullArea.json.
import { io, schema, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** Carbon-authored hull mesh-area record. */
@type.define({ className: "EveSOFDataHullArea", family: "eve" })
export class EveSOFDataHullArea extends CjsModel
{

  /** m_areaType (EveSOFDataArea::AreaType - enum AreaType) [READWRITE, PERSIST, ENUM] */
  @io.persist
  @type.int32
  @schema.enum("AreaType")
  areaType = 0;

  /** m_textures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  textures = [];

  /** m_parameters (PEveSOFDataParameterVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataParameter")
  parameters = [];

  /** m_index (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  index = 0;

  /** m_count (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  count = 1;

  /** m_name (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_shader (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  shader = "";

  /** m_blockedMaterials (uint32_t) [READWRITE, PERSIST] */
  @io.persist
  @type.uint32
  blockedMaterials = 0;

  Assign(config = {})
  {
    config.textures = this.AssignTextures(config.textures);
    config.parameters = this.AssignParameters(config.parameters);
    return config;
  }

  AssignParameters(out = {})
  {
    for (const parameter of this.parameters) parameter.Assign(out);
    return out;
  }

  AssignTextures(out = {})
  {
    for (const texture of this.textures) texture.Assign(out);
    return out;
  }

}
