// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataRaceDamage.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { EveSOFDataParameter } from "../shared/EveSOFDataParameter.js";
import { EveSOFDataTexture } from "../shared/EveSOFDataTexture.js";

/** EveSOFDataRaceDamage (eve) - generated from schema shapeHash 87369617.... */
@type.define({ className: "EveSOFDataRaceDamage", family: "eve" })
export class EveSOFDataRaceDamage extends CjsModel
{

  /** m_armorImpactParameters (PEveSOFDataParameterVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataParameter")
  armorImpactParameters = [];

  /** m_armorImpactTextures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  armorImpactTextures = [];

  /** m_shieldImpactParameters (PEveSOFDataParameterVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataParameter")
  shieldImpactParameters = [];

  /** m_shieldImpactTextures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  shieldImpactTextures = [];

  AssignArmor(out = {})
  {
    out.parameters ??= {};
    out.textures ??= {};
    for (const parameter of this.armorImpactParameters) parameter.Assign(out.parameters);
    for (const texture of this.armorImpactTextures) texture.Assign(out.textures);
    return out;
  }

  AssignShield(out = {})
  {
    out.parameters ??= {};
    out.textures ??= {};
    for (const parameter of this.shieldImpactParameters) parameter.Assign(out.parameters);
    for (const texture of this.shieldImpactTextures) texture.Assign(out.textures);
    return out;
  }

  static combine(base, overrides, out = null)
  {
    out ??= new this();
    base ??= new this();
    EveSOFDataTexture.combineArrays(base.armorImpactTextures, overrides?.armorImpactTextures, out.armorImpactTextures);
    EveSOFDataTexture.combineArrays(base.shieldImpactTextures, overrides?.shieldImpactTextures, out.shieldImpactTextures);
    EveSOFDataParameter.combineArrays(base.armorImpactParameters, overrides?.armorImpactParameters, out.armorImpactParameters);
    EveSOFDataParameter.combineArrays(base.shieldImpactParameters, overrides?.shieldImpactParameters, out.shieldImpactParameters);
    return out;
  }

}
