// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataGenericShader.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSOFDataGenericShader (eve) - generated from schema shapeHash 54379592.... */
@type.define({ className: "EveSOFDataGenericShader", family: "eve" })
export class EveSOFDataGenericShader extends CjsModel
{

  /** m_parameters (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  parameters = [];

  /** m_defaultParameters (PEveSOFDataParameterVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataParameter")
  defaultParameters = [];

  /** m_defaultTextures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  defaultTextures = [];

  /** m_transparencyTextureName (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  transparencyTextureName = "";

  /** m_doGenerateDepthArea (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  doGenerateDepthArea = true;

  /** m_shader (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  shader = "";

  HasUsage(key)
  {
    if (!key) return false;
    return this.transparencyTextureName === key
      || this.defaultParameters.some(value => value?.name === key)
      || this.parameters.some(value => value?.str === key)
      || this.defaultTextures.some(value => value?.name === key);
  }

  get hasPatternMaskMaps()
  {
    return EveSOFDataGenericShader.PatternMaskMaps.some(name =>
      this.defaultTextures.some(value => value?.name === name)
    );
  }

  Assign(config = {}, provided = {})
  {
    config = config || {};
    provided = provided || {};
    config.parameters = this.AssignParameters(config.parameters, provided.parameters);
    config.textures = this.AssignTextures(config.textures, provided.textures);
    return config;
  }

  AssignParameters(out = {}, provided = null)
  {
    out = out || {};
    for (const value of this.defaultParameters)
    {
      value?.Assign?.(out);
    }
    for (const value of this.parameters)
    {
      const name = value?.str;
      if (!name) continue;
      if (provided && Object.hasOwn(provided, name))
      {
        const parameter = provided[name];
        out[name] = Array.isArray(parameter) || ArrayBuffer.isView(parameter)
          ? Array.from(parameter)
          : parameter;
      }
      else if (!Object.hasOwn(out, name))
      {
        out[name] = [0, 0, 0, 1];
      }
    }
    return out;
  }

  AssignTextures(out = {}, provided = null)
  {
    out = out || {};
    for (const value of this.defaultTextures)
    {
      value?.Assign?.(out);
    }
    if (provided && typeof provided === "object") Object.assign(out, provided);
    return out;
  }

  static PatternMaskMaps = Object.freeze([
    "PatternMask1Map",
    "PatternMask2Map"
  ]);

}
