// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataGenericDecalShader.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSOFDataGenericDecalShader (eve) - generated from schema shapeHash ce334d46.... */
@type.define({ className: "EveSOFDataGenericDecalShader", family: "eve" })
export class EveSOFDataGenericDecalShader extends CjsModel
{

  /** m_parameters (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  parameters = [];

  /** m_defaultTextures (PEveSOFDataTextureVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataTexture")
  defaultTextures = [];

  /** m_parentTextures (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  parentTextures = [];

  /** m_additive (bool) [READ, PERSIST] */
  @io.persist
  @type.boolean
  additive = false;

  /** m_shader (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  shader = "";

  HasUsage(key)
  {
    if (!key) return false;
    return this.parameters.some(value => value?.str === key)
      || this.defaultTextures.some(value => value?.name === key)
      || this.parentTextures.some(value => value?.str === key);
  }

  Assign(config = {}, provided = {})
  {
    config = config || {};
    provided = provided || {};
    config.parameters = this.AssignParameters(config.parameters, provided.parameters);
    config.textures = this.AssignTextures(config.textures, provided.textures);
    return config;
  }

  AssignParameters(out = {}, provided = null)
  {
    out = out || {};
    for (const value of this.parameters)
    {
      const name = value?.str;
      if (!name) continue;
      if (provided && Object.hasOwn(provided, name))
      {
        const parameter = provided[name];
        out[name] = Array.isArray(parameter) || ArrayBuffer.isView(parameter)
          ? Array.from(parameter)
          : parameter;
      }
      else if (!Object.hasOwn(out, name))
      {
        out[name] = [0, 0, 0, 1];
      }
    }
    return out;
  }

  AssignTextures(out = {}, provided = null)
  {
    out = out || {};
    for (const value of this.defaultTextures)
    {
      value?.Assign?.(out);
    }
    for (const value of this.parentTextures)
    {
      const name = value?.str;
      if (!name) continue;
      if (provided && Object.hasOwn(provided, name))
      {
        out[name] = provided[name];
      }
      else if (!Object.hasOwn(out, name))
      {
        out[name] = "";
      }
    }
    return out;
  }

}
