// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataGenericSwarm.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";

/** EveSOFDataGenericSwarm (eve) - generated from schema shapeHash 8b492eb6.... */
@type.define({ className: "EveSOFDataGenericSwarm", family: "eve" })
export class EveSOFDataGenericSwarm extends CjsModel
{

  /** m_behavior.m_anchorRadius1 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  anchorRadius1 = 250;

  /** m_behavior.m_anchorRadius0 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  anchorRadius0 = 75;

  /** m_behavior.m_weightCohesion (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightCohesion = 0.1;

  /** m_behavior.m_wanderFluctuation (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  wanderFluctuation = 0.05;

  /** m_behavior.m_separationDistance (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  separationDistance = 250;

  /** m_behavior.m_formationDistance (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  formationDistance = 50;

  /** m_behavior.m_wanderDistance (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  wanderDistance = 100;

  /** m_behavior.m_speed0 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  speed0 = 700;

  /** m_behavior.m_maxDistance0 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  maxDistance0 = 500;

  /** m_behavior.m_maxDistance1 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  maxDistance1 = 125;

  /** m_behavior.m_speedMultiplier (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  speedMultiplier = 1.1;

  /** m_behavior.m_speedMinimum (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  speedMinimum = 10;

  /** m_behavior.m_maxDeceleration (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  maxDeceleration = 200;

  /** m_behavior.m_maxTime (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  maxTime = 0.2;

  /** m_behavior.m_wanderRadius (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  wanderRadius = 80;

  /** m_behavior.m_weightAlign (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightAlign = 50;

  /** m_behavior.m_speed1 (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  speed1 = 1000;

  /** m_behavior.m_weightDecelerate (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightDeceleration = 0.1;

  /** m_behavior.m_weightSeparation (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightSeparation = 0.1;

  /** m_behavior.m_weightAnchor (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightAnchor = 0.5;

  /** m_behavior.m_weightFormation (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightFormation = 1;

  /** m_behavior.m_weightWander (EveSwarm::BehaviorProperties) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  weightWander = 0.33;

}
