// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataGeneric.json.
import { io, schema, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveSOFDataGenericShader } from "./EveSOFDataGenericShader.js";

/** EveSOFDataGeneric (eve) - generated from schema shapeHash 5f2c6dc7.... */
@type.define({ className: "EveSOFDataGeneric", family: "eve" })
export class EveSOFDataGeneric extends CjsModel
{

  /** m_turretAreaType (EveSOFDataArea::AreaType - enum AreaType) [READ, PERSIST, ENUM] */
  @io.persist
  @type.int32
  @schema.enum("AreaType")
  turretAreaType = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_STANDARD] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeSTANDARD = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_KILLCOUNTER] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeKILLCOUNTER = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_HOLE] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeHOLE = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_CYLINDRICAL] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeCYLINDRICAL = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_GLOWCYLINDRICAL] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeGLOWCYLINDRICAL = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_GLOWSTANDARD] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeGLOWSTANDARD = 0;

  /** m_decalMinScreenSizes[EveSOFDataHullDecalSetItem::USAGE_LOGO] (float) [READWRITE, PERSIST] */
  @io.persist
  @type.float32
  decalMinScreenSizeLOGO = 0;

  /** m_shaderPrefix (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  shaderPrefix = "";

  /** m_shaderPrefixAnimated (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  shaderPrefixAnimated = "";

  /** m_variants (PEveSOFDataGenericVariantVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericVariant")
  variants = [];

  /** m_hullCategories (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  hullCategories = [];

  /** m_visibilityGroups (PEveSOFDataVisibilityGroupVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataVisibilityGroup")
  visibilityGroups = [];

  /** m_bannerShader (PEveSOFDataGenericShader) [READ, PERSIST] */
  @io.persist
  @type.struct("EveSOFDataGenericShader")
  bannerShader = new EveSOFDataGenericShader();

  /** m_swarm (EveSOFDataGenericSwarmPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataGenericSwarm")
  swarm = null;

  /** m_damage (EveSOFDataGenericDamagePtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataGenericDamage")
  damage = null;

  /** m_hullDamage (EveSOFDataGenericHullDamagePtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataGenericHullDamage")
  hullDamage = null;

  /** m_genericWreckMaterial (EveSOFDataAreaMaterialPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataAreaMaterial")
  genericWreckMaterial = null;

  /** m_areaShaders (PEveSOFDataGenericShaderVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericShader")
  areaShaders = [];

  /** m_decalShaders (PEveSOFDataGenericDecalShaderVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericDecalShader")
  decalShaders = [];

  /** m_materialPrefixes (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  materialPrefixes = [];

  /** m_patternMaterialPrefixes (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  patternMaterialPrefixes = [];

  /** m_hullCategoryData (PEveSOFDataGenericHullCategoryVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericHullCategory")
  hullCategoriesData = [];

  /** m_areaShaderLocation (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  areaShaderLocation = "";

  /** m_decalShaderLocation (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  decalShaderLocation = "";

  /** m_resPathDefaultAlliance (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  resPathDefaultAlliance = "";

  /** m_resPathDefaultCeo (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  resPathDefaultCeo = "";

  /** m_resPathDefaultCorp (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  resPathDefaultCorp = "";

  HasUnpackedTextures()
  {
    return this.decalShaders.some(shader =>
      shader?.parentTextures?.some(value => value?.str === "NormalMap")
    );
  }

  HasShaderUsage(shaderName, key)
  {
    if (!key) return false;
    const shader = findShader(this.decalShaders, shaderName)
      || findShader(this.areaShaders, shaderName);
    return Boolean(shader?.HasUsage?.(key));
  }

  GetShaderPrefix(isAnimated = false)
  {
    return isAnimated ? this.shaderPrefixAnimated : this.shaderPrefix;
  }

  GetShaderPath(shader, isAnimated = false)
  {
    let path = String(shader ?? "");
    if (!path.startsWith("/")) path = "/" + path;
    const index = path.lastIndexOf("/");
    return path.slice(0, index + 1)
      + this.GetShaderPrefix(isAnimated)
      + path.slice(index + 1);
  }

  GetAreaShaderPath(shader, isAnimated = false)
  {
    return this.areaShaderLocation + this.GetShaderPath(shader, isAnimated);
  }

  GetDecalShaderPath(shader, isAnimated = false)
  {
    return this.decalShaderLocation + this.GetShaderPath(shader, isAnimated);
  }

  HasAreaShader(name)
  {
    return Boolean(findShader(this.areaShaders, name));
  }

  GetAreaShader(name)
  {
    const shader = findShader(this.areaShaders, name);
    if (!shader) throw new ErrSOFAreaShaderNotFound({ name });
    return shader;
  }

  HasDecalShader(name)
  {
    return Boolean(findShader(this.decalShaders, name));
  }

  GetDecalShader(name)
  {
    const shader = findShader(this.decalShaders, name);
    if (!shader) throw new ErrSOFDecalShaderNotFound({ name });
    return shader;
  }

  GetMaterialPrefixes()
  {
    return this.materialPrefixes.map(value => value?.str ?? "");
  }

  GetPatternMaterialPrefixes()
  {
    return this.patternMaterialPrefixes.map(value => value?.str ?? "");
  }

  GetMaterialPrefix(index)
  {
    const value = this.materialPrefixes[Number(index) - 1];
    if (!value) throw new ErrSOFMaterialPrefixNotFound({ index });
    return value.str;
  }

  GetPatternMaterialPrefix(index)
  {
    const value = this.patternMaterialPrefixes[Number(index) - 1];
    if (!value) throw new ErrSOFPatternMaterialPrefixNotFound({ index });
    return value.str;
  }

}

export class ErrSOFAreaShaderNotFound extends Error
{
  constructor({ name = "" } = {})
  {
    super("SOF area shader not found: " + name);
    this.name = "ErrSOFAreaShaderNotFound";
    this.code = "EVE_SOF_AREA_SHADER_NOT_FOUND";
    this.shader = name;
  }
}

export class ErrSOFDecalShaderNotFound extends Error
{
  constructor({ name = "" } = {})
  {
    super("SOF decal shader not found: " + name);
    this.name = "ErrSOFDecalShaderNotFound";
    this.code = "EVE_SOF_DECAL_SHADER_NOT_FOUND";
    this.shader = name;
  }
}

export class ErrSOFMaterialPrefixNotFound extends Error
{
  constructor({ index = -1 } = {})
  {
    super("SOF material prefix not found: " + index);
    this.name = "ErrSOFMaterialPrefixNotFound";
    this.code = "EVE_SOF_MATERIAL_PREFIX_NOT_FOUND";
    this.index = index;
  }
}

export class ErrSOFPatternMaterialPrefixNotFound extends Error
{
  constructor({ index = -1 } = {})
  {
    super("SOF pattern material prefix not found: " + index);
    this.name = "ErrSOFPatternMaterialPrefixNotFound";
    this.code = "EVE_SOF_PATTERN_MATERIAL_PREFIX_NOT_FOUND";
    this.index = index;
  }
}

function findShader(values, name)
{
  if (!name || !Array.isArray(values)) return null;
  return values.find(value => value?.shader === name) || null;
}
