// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataPatternPerHull.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveSOFDataPatternTransform } from "./EveSOFDataPatternTransform.js";

/** EveSOFDataPatternPerHull (eve) - generated from schema shapeHash ba16415a.... */
@type.define({ className: "EveSOFDataPatternPerHull", family: "eve" })
export class EveSOFDataPatternPerHull extends CjsModel
{

  /** m_transformLayer1 (EveSOFDataPatternTransformPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataPatternTransform")
  transformLayer1 = null;

  /** m_transformLayer2 (EveSOFDataPatternTransformPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataPatternTransform")
  transformLayer2 = null;

  /** m_name (BlueSharedString) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  constructor(name = "")
  {
    super();
    this.name = name;
  }

  Empty()
  {
    this.transformLayer1?.Empty();
    this.transformLayer2?.Empty();
    return this;
  }

  Flip()
  {
    [this.transformLayer1, this.transformLayer2] = [this.transformLayer2, this.transformLayer1];
    return this;
  }

  SetFromCustomMasks(customMask1, customMask2)
  {
    this.SetTransformLayer1FromCustomMask(customMask1);
    this.SetTransformLayer2FromCustomMask(customMask2);
    return this;
  }

  SetTransformLayer1FromCustomMask(customMask)
  {
    this.transformLayer1 = setTransformFromCustomMask(this.transformLayer1, customMask);
    return this;
  }

  SetTransformLayer2FromCustomMask(customMask)
  {
    this.transformLayer2 = setTransformFromCustomMask(this.transformLayer2, customMask);
    return this;
  }

}

function setTransformFromCustomMask(transform, customMask)
{
  if (!customMask) return null;
  return (transform ?? new EveSOFDataPatternTransform()).SetFromCustomMask(customMask);
}
