// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataPattern.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";
import { EveSOFDataPatternLayer } from "./EveSOFDataPatternLayer.js";
import { EveSOFDataPatternPerHull } from "./EveSOFDataPatternPerHull.js";

/** EveSOFDataPattern (eve) - generated from schema shapeHash f8a30280.... */
@type.define({ className: "EveSOFDataPattern", family: "eve" })
export class EveSOFDataPattern extends CjsModel
{

  /** m_projections (PEveSOFDataPatternPerHullVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataPatternPerHull")
  projections = [];

  /** m_applicationGroups (PEveSOFDataPatternApplicationGroupVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataPatternApplicationGroup")
  applicationGroups = [];

  /** m_layer1 (EveSOFDataPatternLayerPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataPatternLayer")
  layer1 = null;

  /** m_layer2 (EveSOFDataPatternLayerPtr) [READWRITE, PERSIST] */
  @io.persist
  @type.objectRef("EveSOFDataPatternLayer")
  layer2 = null;

  /** m_name (std::string) [READWRITE, PERSIST] */
  @io.persist
  @type.string
  name = "";

  /** m_sof6 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  sof6 = false;

  Has(hullName)
  {
    return this.IndexOfProjection(hullName) !== -1;
  }

  Get(hullName)
  {
    const index = this.IndexOfProjection(hullName);
    if (index === -1)
    {
      throw new ErrSOFProjectionNotFound({ pattern: this.name, projection: hullName });
    }
    const projection = this.projections[index];
    return {
      name: this.name,
      layer1: this.layer1,
      layer2: this.layer2,
      transformLayer1: projection.transformLayer1,
      transformLayer2: projection.transformLayer2
    };
  }

  IndexOfProjection(hullName)
  {
    const name = String(hullName ?? "").toUpperCase();
    return this.projections.findIndex(value => String(value?.name ?? "").toUpperCase() === name);
  }

  EmptyLayers()
  {
    this.layer1?.Empty();
    this.layer2?.Empty();
    return this;
  }

  FlipLayers()
  {
    [this.layer1, this.layer2] = [this.layer2, this.layer1];
    return this;
  }

  FlipTransformLayers()
  {
    this.projections.forEach(projection => projection?.Flip());
    return this;
  }

  Flip()
  {
    this.FlipLayers();
    this.FlipTransformLayers();
    return this;
  }

  SetLayersFromCustomMasks(customMask1, customMask2)
  {
    this.layer1 = setLayerFromCustomMask(this.layer1, customMask1, "PatternMask1Map");
    this.layer2 = setLayerFromCustomMask(this.layer2, customMask2, "PatternMask2Map");
    return this;
  }

  SetHullProjectionFromCustomMasks(hullName, customMask1, customMask2)
  {
    if (!hullName) throw new TypeError("EveSOFDataPattern requires a hull name");
    const index = this.IndexOfProjection(hullName);
    const projection = index === -1
      ? new EveSOFDataPatternPerHull(hullName)
      : this.projections[index];
    if (index === -1) this.projections.push(projection);
    projection.SetFromCustomMasks(customMask1, customMask2);
    return projection;
  }

}

export class ErrSOFProjectionNotFound extends Error
{
  constructor({ pattern = "", projection = "" } = {})
  {
    super("SOF pattern projection '" + projection + "' not found for pattern '" + pattern + "'");
    this.name = "ErrSOFProjectionNotFound";
    this.code = "EVE_SOF_PROJECTION_NOT_FOUND";
    this.pattern = pattern;
    this.projection = projection;
  }
}

function setLayerFromCustomMask(layer, customMask, textureName)
{
  if (!customMask) return null;
  return (layer ?? new EveSOFDataPatternLayer(textureName)).SetFromCustomMask(customMask);
}
