// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataPatternMaterialOverride.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSOFDataPatternMaterialOverride (eve) - generated from schema shapeHash ce565030.... */
@type.define({ className: "EveSOFDataPatternMaterialOverride", family: "eve" })
export class EveSOFDataPatternMaterialOverride extends CjsModel
{

  /** m_isTargetMtl1 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  isTargetMtl1 = true;

  /** m_isTargetMtl2 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  isTargetMtl2 = true;

  /** m_isTargetMtl3 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  isTargetMtl3 = true;

  /** m_isTargetMtl4 (bool) [READWRITE, PERSIST] */
  @io.persist
  @type.boolean
  isTargetMtl4 = true;

  GetTargets(out = [])
  {
    out[0] = this.isTargetMtl1;
    out[1] = this.isTargetMtl2;
    out[2] = this.isTargetMtl3;
    out[3] = this.isTargetMtl4;
    return out;
  }

}
