// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataFactionVisibilityGroupSet.json.
import { io, type } from "@carbonenginejs/runtime-utils/schema";
import { CjsModel } from "@carbonenginejs/runtime-utils/model";

/** EveSOFDataFactionVisibilityGroupSet (eve) - generated from schema shapeHash da3a6331.... */
@type.define({ className: "EveSOFDataFactionVisibilityGroupSet", family: "eve" })
export class EveSOFDataFactionVisibilityGroupSet extends CjsModel
{

  /** m_visibilityGroups (PEveSOFDataGenericStringVector) [READ, PERSIST] */
  @io.persist
  @type.list("EveSOFDataGenericString")
  visibilityGroups = [];

  IsObjectVisible(value)
  {
    if (!value || typeof value !== "object") return false;
    return this.Has(value.visibilityGroup);
  }

  Has(visibilityGroup)
  {
    if (typeof visibilityGroup !== "string") return false;
    const normalized = visibilityGroup ? visibilityGroup.toUpperCase() : "PRIMARY";
    return this.visibilityGroups.some(value =>
    {
      const group = typeof value === "string" ? value : value?.str;
      return typeof group === "string" && group.toUpperCase() === normalized;
    });
  }

}
