// Ported from CarbonEngine (MIT, (c) 2026 CCP Games) - https://github.com/carbonengine/trinity
//   trinity/trinity/Eve/SpaceObjectFactory/EveSOFData.h
// Generated by format-carbon carbon-class --emit. Verify against eve/EveSOFDataFactionColorSet.json.
import { io, type } from "@carbonenginejs/core-types/schema";
import { CjsModel } from "@carbonenginejs/core-types/model";
import { vec4 } from "@carbonenginejs/core-math/vec4";

/** EveSOFDataFactionColorSet (eve) - generated from schema shapeHash 715e3a12.... */
@type.define({ className: "EveSOFDataFactionColorSet", family: "eve" })
export class EveSOFDataFactionColorSet extends CjsModel
{

  /** m_colors[SOFDataFactionColorChooser::TYPE_KILLMARK] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Killmark = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_FORCEFIELD] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryForcefield = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY_FORCEFIELD] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  SecondaryForcefield = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryFx = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  SecondaryFx = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_WARP_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryWarpFx = vec4.fromValues(1, 99 / 255, 51 / 255, 1);

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_ATTACK_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryAttackFX = vec4.fromValues(1, 24 / 255, 11 / 255, 1);

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_SIEGE_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimarySiegeFX = vec4.fromValues(1, 94 / 255, 45 / 255, 1);

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_DOCKED_FX] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryDockedFX = vec4.fromValues(76 / 255, 130 / 255, 226 / 255, 1);

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Primary = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Secondary = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_TERTIARY] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Tertiary = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_BLACK] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Black = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_WHITE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  White = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_YELLOW] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Yellow = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_ORANGE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Orange = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_RED] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Red = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_BLUE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Blue = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_GREEN] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Green = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_CYAN] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Cyan = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_FIRE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Fire = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_HOLOGRAM] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryHologram = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY_HOLOGRAM] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  SecondaryHologram = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_TERTIARY_HOLOGRAM] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  TertiaryHologram = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_LIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryLight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY_LIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  SecondaryLight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_TERTIARY_LIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  TertiaryLight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_WHITE_LIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  WhiteLight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_HULL] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Hull = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_GLASS] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Glass = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_REACTOR] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Reactor = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_DARKHULL] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Darkhull = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_BOOSTER] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  Booster = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_BANNER] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryBanner = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_BILLBOARD] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimaryBillboard = vec4.fromValues(2.5, 2.5, 2.5, 2.5);

  /** m_colors[SOFDataFactionColorChooser::TYPE_PRIMARY_SPOTLIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  PrimarySpotlight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_SECONDARY_SPOTLIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  SecondarySpotlight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_TERTIARY_SPOTLIGHT] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  TertiarySpotlight = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_0] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  State0 = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_1] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  State1 = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_2] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  State2 = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_3] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  State3 = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_VULNERABLE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  StateVulnerable = vec4.createLinear();

  /** m_colors[SOFDataFactionColorChooser::TYPE_STATE_INVULNERABLE] (Color) [READWRITE, PERSIST] */
  @io.persist
  @type.color
  StateInvulnerable = vec4.createLinear();


  Has(type)
  {
    const name = this.constructor.Types[type];
    if (name === undefined) throw new ErrSOFFactionColorSetTypeUnknown(type);
    return this[name] !== null && this[name] !== undefined;
  }

  Get(type, out)
  {
    if (!out) throw new TypeError("Get requires an output vector");
    if (!this.Has(type)) throw new ErrSOFFactionColorSetTypeNotFound(type);
    return vec4.copy(out, this[this.constructor.Types[type]]);
  }

  static ColorType = Object.freeze({
    TYPE_PRIMARY: 0,
    TYPE_SECONDARY: 1,
    TYPE_TERTIARY: 2,
    TYPE_BLACK: 3,
    TYPE_WHITE: 4,
    TYPE_YELLOW: 5,
    TYPE_ORANGE: 6,
    TYPE_RED: 7,
    TYPE_BLUE: 8,
    TYPE_GREEN: 9,
    TYPE_CYAN: 10,
    TYPE_FIRE: 11,
    TYPE_HULL: 12,
    TYPE_GLASS: 13,
    TYPE_REACTOR: 14,
    TYPE_DARKHULL: 15,
    TYPE_BOOSTER: 16,
    TYPE_KILLMARK: 17,
    TYPE_PRIMARY_LIGHT: 18,
    TYPE_SECONDARY_LIGHT: 19,
    TYPE_TERTIARY_LIGHT: 20,
    TYPE_WHITE_LIGHT: 21,
    TYPE_PRIMARY_HOLOGRAM: 22,
    TYPE_SECONDARY_HOLOGRAM: 23,
    TYPE_TERTIARY_HOLOGRAM: 24,
    TYPE_STATE_0: 25,
    TYPE_STATE_1: 26,
    TYPE_STATE_2: 27,
    TYPE_STATE_3: 28,
    TYPE_STATE_VULNERABLE: 29,
    TYPE_STATE_INVULNERABLE: 30,
    TYPE_PRIMARY_FORCEFIELD: 31,
    TYPE_SECONDARY_FORCEFIELD: 32,
    TYPE_PRIMARY_BANNER: 33,
    TYPE_PRIMARY_FX: 34,
    TYPE_SECONDARY_FX: 35,
    TYPE_PRIMARY_SPOTLIGHT: 36,
    TYPE_SECONDARY_SPOTLIGHT: 37,
    TYPE_TERTIARY_SPOTLIGHT: 38,
    TYPE_PRIMARY_BILLBOARD: 39,
    TYPE_PRIMARY_WARP_FX: 40,
    TYPE_PRIMARY_ATTACK_FX: 41,
    TYPE_PRIMARY_SIEGE_FX: 42,
    TYPE_PRIMARY_DOCKED_FX: 43,
    TYPE_MAX: 44
  });

  static Types = Object.freeze([
    "Primary",
    "Secondary",
    "Tertiary",
    "Black",
    "White",
    "Yellow",
    "Orange",
    "Red",
    "Blue",
    "Green",
    "Cyan",
    "Fire",
    "Hull",
    "Glass",
    "Reactor",
    "Darkhull",
    "Booster",
    "Killmark",
    "PrimaryLight",
    "SecondaryLight",
    "TertiaryLight",
    "WhiteLight",
    "PrimaryHologram",
    "SecondaryHologram",
    "TertiaryHologram",
    "State0",
    "State1",
    "State2",
    "State3",
    "StateVulnerable",
    "StateInvulnerable",
    "PrimaryForcefield",
    "SecondaryForcefield",
    "PrimaryBanner",
    "PrimaryFx",
    "SecondaryFx",
    "PrimarySpotlight",
    "SecondarySpotlight",
    "TertiarySpotlight",
    "PrimaryBillboard",
    "PrimaryWarpFx",
    "PrimaryAttackFX",
    "PrimarySiegeFX",
    "PrimaryDockedFX"
  ]);

}

export class ErrSOFFactionColorSetTypeUnknown extends RangeError
{
  constructor(type)
  {
    super("SOF faction color set type unknown (" + type + ")");
    this.name = "ErrSOFFactionColorSetTypeUnknown";
    this.code = "EVE_SOF_FACTION_COLOR_TYPE_UNKNOWN";
    this.type = type;
  }
}

export class ErrSOFFactionColorSetTypeNotFound extends Error
{
  constructor(type)
  {
    super("SOF faction color set type not found (" + type + ")");
    this.name = "ErrSOFFactionColorSetTypeNotFound";
    this.code = "EVE_SOF_FACTION_COLOR_TYPE_NOT_FOUND";
    this.type = type;
  }
}

